/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        surface: "#0b1326",
        "surface-dim": "#0b1326",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-bright": "#31394d",
        "surface-variant": "#2d3449",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#c7c4d7",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-primary": "#494bd6",
        secondary: "#e9c349",
        "on-secondary": "#3c2f00",
        "secondary-container": "#af8d11",
        "on-secondary-container": "#342800",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#574500",
        tertiary: "#ffb783",
        "on-tertiary": "#4f2500",
        "tertiary-container": "#d97721",
        "on-tertiary-container": "#452000",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-fixed-dim": "#ffb783",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#703700",
        outline: "#908fa0",
        "outline-variant": "#464554",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "surface-tint": "#c0c1ff",
        "semantic-success": "#5eead4",
        "semantic-warning": "#fbbf24",
        "semantic-danger": "#fb7185",
        "semantic-info": "#93c5fd",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Newsreader", "Georgia", "serif"],
        label: ["Manrope", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      boxShadow: {
        glow: "0 40px 60px -15px rgba(192, 193, 255, 0.1)",
        glowSm: "40px 0 60px -15px rgba(192, 193, 255, 0.06)",
        primarySoft: "0 0 20px rgba(192, 193, 255, 0.25)",
      },
      maxWidth: {
        read: "650px",
      },
    },
  },
  plugins: [],
};
