"""Workflow tuning constants."""

# Max unfinished anchors shown in director / planner prompts (sliding window).
VISIBLE_UNACHIEVED_ANCHOR_LIMIT = 5

# Planner prompt: cap unbounded fields (chars).
AUTHOR_CHAPTER_PLAN_MAX_CHARS = 2000
CHAPTER_HARD_RULES_MAX_CHARS = 8000

PLANNER_PREVIOUS_CHAPTER_SUMMARY_CAP = 2000
PLANNER_RECENT_CHAPTER_CONTEXT_CAP = 2500
PLANNER_VOLUME_SUMMARY_CAP = 1500
PLANNER_BIBLE_CONTEXT_CAP = 1200
LOCAL_ENFORCED_RULES_CONTEXT_CAP = 3000
PLANNER_GRAPH_CONTEXT_CAP = 1800
PLANNER_VECTOR_CONTEXT_CAP = 1200
PLANNER_PREVIOUS_NARRATIVE_CAP = 2200
PLANNER_UPCOMING_ANCHORS_JSON_CAP = 4000
PLANNER_PRIOR_FEEDBACK_MAX_ITEMS = 8
PLANNER_CONTINUITY_NOTE_MAX_ITEMS = 24
PLANNER_CONTINUITY_NOTE_MAX_CHARS = 400
PLANNER_ENTITY_NAME_MAX_ITEMS = 40
PLANNER_ENTITY_NAME_MAX_CHARS = 120

# Plan supervisor prompt: cap embedded payload JSON.
PLAN_SUPERVISOR_PREVIOUS_SUMMARY_CAP = 2000
PLAN_SUPERVISOR_RECENT_CONTEXT_CAP = 2200
PLAN_SUPERVISOR_NARRATIVE_SCRIPT_CAP = 3500
PLAN_SUPERVISOR_GRAPH_CAP = 2000
PLAN_SUPERVISOR_VECTOR_CAP = 1200
PLAN_SUPERVISOR_BIBLE_CAP = 1200
PLAN_SUPERVISOR_ENDING_BOUNDARY_CAP = 800
PLAN_SUPERVISOR_BEAT_STRING_CAP = 500
PLAN_SUPERVISOR_EVENT_DESC_CAP = 600
PLAN_SUPERVISOR_MAX_BEATS_IN_PROMPT = 12
PLAN_SUPERVISOR_MAX_EVENTS_IN_PROMPT = 14

# Macro: each volume must end up with this many anchors after normalization.
MIN_ANCHORS_PER_VOLUME = 3
MAX_ANCHORS_PER_VOLUME = 5
